import type { Metadata } from "next";
import { Alegreya, Comic_Neue} from 'next/font/google'
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import { cookies } from "next/headers";

const alegreya = Alegreya({
  subsets: ['latin'],
  variable: '--font-alegreya',
})

const comic_neue = Comic_Neue({
  subsets: ['latin'],
  weight: '700',
  variable: '--font-comic_neue'
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const loggedUsername = cookies().get('SocialUsername')

  return (
    <html lang="en" className={`${comic_neue.variable} ${alegreya.variable}`}>
      <body>
        <Navbar loggedUsername={loggedUsername?.value}/>
        {children}
      </body>
    </html>
  );
}
